"""create_activities_table

Revision ID: 38c9e7213a31
Revises: d34f511c9a9d
Create Date: 2024-10-02 11:35:44.503200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38c9e7213a31'
down_revision: Union[str, None] = 'd34f511c9a9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('link_classroom', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('schedule_items_ibfk_1', 'schedule_items', type_='foreignkey')
    op.create_foreign_key(None, 'schedule_items', 'schedules', ['schedule_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedule_items', type_='foreignkey')
    op.create_foreign_key('schedule_items_ibfk_1', 'schedule_items', 'schedules', ['schedule_id'], ['id'], ondelete='CASCADE')
    op.drop_table('activities')
    # ### end Alembic commands ###
